apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shophub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.config.jwtSecret | quote }}
  db-password: {{ .Values.config.db.password | quote }}
